// React/rt20.create-reate-project/reactprj01/src/containers/todo/components/TodoList.js
import React, { useState, useRef } from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components';

const StyledTodoList = styled.section`
  ul {
    list-style-type: none;
    padding-left: 0px;
    margin-top: 0;
    text-align: left;
  }

  li {
    display: flex;
    min-height: 50px;
    height: 50px;
    line-height: 50px;
    margin: 0.5rem 0;
    padding: 0 0.9rem;
    background: white;
    border-radius: 5px;
  }

  li.checked {
    background: #bbb;
    color: #fff;
    text-decoration: line-through;
  }

  .checkBtn {
    line-height: 45px;
    color: #62acde;
    margin-right: 5px;
  }

  .saveBtn {
    margin-left: auto;
    color: #3f7fbf;
  }

  .modifyBtn {
    margin-left: auto;
    color: #bf9f3f;
  }

  .removeBtn {
    margin-left: 10px;
    color: #de4343;
  }

  .list-enter-active,
  .list-leave-active {
    transition: all 1s;
  }

  .list-enter,
  .list-leave-to {
    opacity: 0;
    transform: translateY(30px);
  }
`;

function TodoList({ todoItems, callbackDoneToggle, callbackSaveToggle, callbackModifyToggle, callbackRemoveTodo }) {
  const refInputTodo = useRef(null);

  const handlerDoneToggle = (e) => {
    // click 이벤트 취소. 버블링 방지
    //
    const id = Number(e.target.dataset.id); // data-id. Number() : 문자열을 숫자로 변환
    const item = JSON.parse(e.target.dataset.item); // data-item

    e.stopPropagation(); // click 이벤트 취소. 버블링 막기

    // 부모 컴포넌트의 콜백 메서드 callbackDoneToggle 호출
    callbackDoneToggle(id);
  };

  const handlerSaveToggle = (e) => {
    // click 이벤트 취소. 버블링 방지
    //
    const id = Number(e.target.closest('li').dataset.id); // data-id. Number() : 문자열을 숫자로 변환
    const item = JSON.parse(e.target.closest('li').dataset.item); // data-item
    console.log(id);
    e.stopPropagation(); // click 이벤트 취소. 버블링 막기
    const todo = refInputTodo.current.value;
    console.log(todo);

    // 부모 컴포넌트의 콜백 메서드 callbackDoneToggle 호출
    callbackSaveToggle(id, todo);
  };

  const handlerModifyToggle = (e) => {
    // click 이벤트 취소. 버블링 방지
    //
    const id = Number(e.target.closest('li').dataset.id); // data-id. Number() : 문자열을 숫자로 변환
    const item = JSON.parse(e.target.closest('li').dataset.item); // data-item
    console.log(id);
    e.stopPropagation(); // click 이벤트 취소. 버블링 막기

    // 부모 컴포넌트의 콜백 메서드 callbackDoneToggle 호출
    callbackModifyToggle(id);
  };

  const handlerRemoveTodo = (e, id) => {
    // 부모 컴포넌트의 콜백 메서드 callbackRemoveTodo 호출
    callbackRemoveTodo(id);
  };

  let list =
    todoItems &&
    todoItems.map((item) => (
      <li
        key={item.id}
        className={item.done ? 'checked' : null}
        data-id={item.id}
        data-item={JSON.stringify(item)}
        onClick={handlerDoneToggle}
      >
        <i aria-hidden="true" className="checkBtn fas fa-check"></i>
        {item.modify ? (
          <input
            type="text"
            ref={refInputTodo}
            defaultValue={item.todo}
            onClick={(e) => e.stopPropagation()}
            onKeyUp={(e) => e.keyCode === 13 && handlerSaveToggle(e)}
          />
        ) : (
          item.todo
        )}
        {item.modify ? (
          <span type="button" className="saveBtn" onClick={handlerSaveToggle}>
            <i aria-hidden="true" className="far fa-save"></i>
          </span>
        ) : (
          <span type="button" className="modifyBtn" onClick={handlerModifyToggle}>
            <i aria-hidden="true" className="far fa-edit"></i>
          </span>
        )}
        <span
          type="button"
          className="removeBtn"
          onClick={(e) => {
            e.stopPropagation(); // 이벤트 취소. 버블링 방지

            // 부모 컴포넌트의 콜백 메서드 callbackDoneToggle 호출
            handlerRemoveTodo(e, item.id);
          }}
        >
          <i aria-hidden="true" className="far fa-trash-alt"></i>
        </span>
      </li>
    ));
  return (
    <StyledTodoList>
      <ul>{list}</ul>
    </StyledTodoList>
  );
}

TodoList.propTypes = {
  // props의 프로퍼티 타입 설정. https://ko.reactjs.org/docs/typechecking-with-proptypes.html
  // 인자명: PropTypes.func.isRequired,
  // 인자명: PropTypes.arrayOf(PropTypes.object),
  todoItems: PropTypes.array.isRequired,
  callbackDoneToggle: PropTypes.func.isRequired,
  callbackSaveToggle: PropTypes.func.isRequired,
  callbackModifyToggle: PropTypes.func.isRequired,
  handlerRemoveTodo: PropTypes.func.isRequired,
};
TodoList.defaultProps = {
  // props의 디폴트 값 설정. https://ko.reactjs.org/docs/typechecking-with-proptypes.html
  // 인자명: () => {},
  // 인자명: [],
  todoItems: [],
  callbackDoneToggle: () => {},
  callbackSaveToggle: () => {},
  callbackModifyToggle: () => {},
  handlerRemoveTodo: () => {},
};

export default React.memo(TodoList); // React.memo()는 props 미변경시 컴포넌트 리렌더링 방지 설정

// Vuejs/vue30컴포넌트실습/comprj01/src/components/todo/TodoList.vue
<style scoped>
ul {
  list-style-type: none;
  padding-left: 0px;
  margin-top: 0;
  text-align: left;
}
li {
  display: flex;
  min-height: 50px;
  height: 50px;
  line-height: 50px;
  margin: 0.5rem 0;
  padding: 0 0.9rem;
  background: white;
  border-radius: 5px;
}
li.checked {
  background: #bbb;
  color: #fff;
  text-decoration: line-through;
}
.checkBtn {
  line-height: 45px;
  color: #62acde;
  margin-right: 5px;
}
.removeBtn {
  margin-left: auto;
  color: #de4343;
}

.list-enter-active,
.list-leave-active {
  transition: all 1s;
}
.list-enter,
.list-leave-to {
  opacity: 0;
  transform: translateY(30px);
}
</style>

<template>
  <section>
    <transition-group name="list" tag="ul">
      <li
        v-for="todoItem in todoItems"
        v-bind:key="todoItem.id"
        v-bind:class="checked(todoItem.done)"
        v-on:click="doneToggle(todoItem.id)"
      >
        <i class="checkBtn fas fa-check" aria-hidden="true"></i>
        {{ todoItem.todo }}
        <span
          class="removeBtn"
          type="button"
          v-on:click="removeTodo(todoItem.id)"
        >
          <i class="far fa-trash-alt" aria-hidden="true"></i>
        </span>
      </li>
    </transition-group>
  </section>
</template>

<script>
// vuex 라이브러리에서 mapActions, mapMutations, mapState, mapGetters 함를 가져옵니다.
// import { mapActions, mapMutations, mapState, mapGetters } from 'vuex';

export default {
  /* pdtmc^2w */
  props: ['todoItems'],
  data() {
    /* 컴포넌트 안에서 사용되는 변수 등록. 개별 변수 */
    return {};
  },
  //template: ``,
  methods: {
    /* 이벤트 핸들러 등록 + 일반 함수 */
    /* vuex 를 사용하는 경우
      mapActions 는 store의 actions 를 가져오는 헬퍼 메서드입니다.
      namespaced: true를 설정한 경우 네임스페이스를 사용하기 때문에 store의 모듈 명을 적어주어야 합니다.
      store 모듈에서 actions 를 가져오는 2가지 방식
      1) store.모듈명.actions 이름 바꾸어 사용하기(추천방식)
         ...mapActions('모듈명', { dispatch액션명1: '액션명1', dispatch액션명2: '액션명2' }),
      2) store.모듈명.actions 이름 그대로 사용하기
         ...mapActions('모듈명', ['액션명1', '액션명2']),
      */
    checked(done) {
      if (done) {
        return 'checked'; // 또는 {checked: true}
      } else {
        return null; // 또는 {checked: false}
      }
    },
    doneToggle(id) {
      this.$emit('doneToggle', id);
    },
    removeTodo(id) {
      this.$emit('removeTodo', id);
    },
  },
  components: {
    /* 전역 컴포넌트인 경우는 등록하지 않는다. 전역 컴포넌트는 프로토타입 체인으로 찾을 수 있기 때문에 */
    /* 지역 컴포넌트나 파일 컴포넌트만 등록 한다. 예시) "태그명" : 컴포넌트명 */
  },
  computed: {
    /* 자동처리 + 동기식. 메서드로 작성. return 필수. data 와 공존 불가 */
    /* vuex 를 사용하는 경우
      mapGetters 는 store의 getters 를 가져오는 헬퍼메서드입니다.
      namespaced: true를 설정한 경우 네임스페이스를 사용하기 때문에 store의 모듈 명을 적어주어야 합니다.
      store 모듈에서 getters 를 가져오는 2가지 방식
      1) store.모듈명.getters 이름 바꾸어 사용하기
         ...mapGetters('모듈명', { get게터명1: '게터명1', get게터명2: '게터명2' }),
      2) store.모듈명.getters 이름 그대로 사용하기(추천방식)
         ...mapGetters('모듈명', ['게터명1', '게터명2']),
      */
  },
  watch: {
    /* 자동처리 + 비동기식. data 에 등록된 프로퍼티(변수) 모니터링. 메서드로 작성. 매개변수 필수. 외부 api 호출을 위해서 사용 */
  },
  created() {
    console.log('created');
  },
  mounted() {
    console.log('mounted');
    /* store의 actions 호출 */
    // this.$store.dispatch('액션명', payload);
  },
  updated() {
    console.log('updated');
  },
};
</script>
